version: '3.9'

services:
  node_app:
    container_name: micro
    build: .
    image: alejandro048/microser
    ports:
    - "3001:3001"
    environment:
      - PG_DB=test
      - PG_USER=parko
      - PG_PASSWORD=12345
      - PG_HOST=node_db

    depends_on:
      - node_db
    restart: always

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=parko
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/posgresql/data

volumes:
  node_db_data: {}
